import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
import { ThemeProvider } from "@/components/theme-provider"
import { NavigationMenuDemo } from "@/components/ui/navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="">
          
            <div id="navbar" className="pt-8 pl-8"><NavigationMenuDemo /></div>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}

